name: Release
run-name: Release for ${{ github.ref }}

on:
  release:
    types: [created]

jobs:
  major-tag:
    name: "Update Major Tag"
    permissions: 
        contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git Credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Push 
        run: |
          VERSION=${{ github.ref_name }}
          MAJOR=${VERSION%%.*}

          echo "Updating tag ${MAJOR} to ${GITHUB_SHA}"

          git tag -f ${MAJOR}
          git push origin ${MAJOR} --force
