name: "Tests"
on:
  push:
    branches: main
    paths: action.yml
  pull_request:
    branches: main
    paths: action.yml
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  action:
    name: "Action"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        branch: [latest, stg]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run action
        uses: ./
        with:
          branch: ${{ matrix.branch }}
          
      - name: Test that DALAMUD_HOME is set
        shell: bash
        run: |
          if [ -z "DALAMUD_HOME" ]; then
            echo "::error DALAMUD was not set after running the installer."
            exit 1
          fi

      - name: Test that there are files at DALAMUD_HOME
        shell: bash
        run: |
          ls -ll $DALAMUD_HOME
          if [ ! -d "$DALAMUD_HOME" ]; then
            echo "::error DALAMUD had no files located at its path after running the installer."
            exit 1
          fi

